In [760]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split 
from sklearn.metrics import mutual_info_score
from sklearn.feature_extraction import DictVectorizer                
from sklearn.linear_model import LogisticRegression

In [761]:
data = 'https://raw.githubusercontent.com/alexeygrigorev/datasets/master/course_lead_scoring.csv'
!wget $data

--2025-10-10 09:12:04--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/course_lead_scoring.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 80876 (79K) [text/plain]
Saving to: ‘course_lead_scoring.csv.22’

course_lead_scoring 100%[===================>]  78.98K  --.-KB/s    in 0.02s

2025-10-10 09:12:04 (4.98 MB/s) - ‘course_lead_scoring.csv.22’ saved [80876/80876]

In [762]:
df = pd.read_csv(data)
df.head()

,lead_source,industry,number_of_courses_viewed,annual_income,employment_status,location,interaction_count,lead_score,converted
0,paid_ads,NaN,1,79450.0,unemployed,south_america,4,0.94,1
1,social_media,retail,1,46992.0,employed,south_america,1,0.80,0
2,events,healthcare,5,78796.0,unemployed,australia,3,0.69,1
3,paid_ads,retail,2,83843.0,NaN,australia,1,0.87,0
4,referral,education,3,85012.0,self_employed,europe,3,0.62,1

In [763]:
df.columns = df.columns.str.lower().str.replace(' ', '_')
categorical_columns = list(df.dtypes[df.dtypes == 'object'].index)
for c in categorical_columns:
    df[c] = df[c].str.lower().str.replace(' ', '_')

In [764]:
df.isnull().sum()

lead_source                 128
industry                    134
number_of_courses_viewed      0
annual_income               181
employment_status           100
location                     63
interaction_count             0
lead_score                    0
converted                     0
dtype: int64

In [765]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1462 entries, 0 to 1461
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   lead_source               1334 non-null   object
 1   industry                  1328 non-null   object
 2   number_of_courses_viewed  1462 non-null   int64
 3   annual_income             1281 non-null   float64
 4   employment_status         1362 non-null   object
 5   location                  1399 non-null   object
 6   interaction_count         1462 non-null   int64
 7   lead_score                1462 non-null   float64
 8   converted                 1462 non-null   int64
dtypes: float64(2), int64(3), object(4)
memory usage: 102.9+ KB

In [766]:
df_filled = df.copy()
for col in categorical:
    df_filled[col] = df_filled[col].fillna('NA')
for col in numerical:
    df_filled[col] = df_filled[col].fillna(0.0)

In [767]:
df.isnull().sum()

lead_source                 128
industry                    134
number_of_courses_viewed      0
annual_income               181
employment_status           100
location                     63
interaction_count             0
lead_score                    0
converted                     0
dtype: int64

In [768]:
df.industry.value_counts()

industry
retail           203
finance          200
other            198
healthcare       187
education        187
technology       179
manufacturing    174
Name: count, dtype: int64

In [769]:
numerical = ['number_of_courses_viewed', 'interaction_count', 'lead_score']
categorical = ['lead_source', 'industry', 'employment_status', 'location']
features = numerical + categorical

In [770]:
df.head(9)

,lead_source,industry,number_of_courses_viewed,annual_income,employment_status,location,interaction_count,lead_score,converted
0,paid_ads,NaN,1,79450.0,unemployed,south_america,4,0.94,1
1,social_media,retail,1,46992.0,employed,south_america,1,0.80,0
2,events,healthcare,5,78796.0,unemployed,australia,3,0.69,1
3,paid_ads,retail,2,83843.0,NaN,australia,1,0.87,0
4,referral,education,3,85012.0,self_employed,europe,3,0.62,1
5,events,manufacturing,1,59904.0,NaN,africa,6,0.83,1
6,social_media,technology,0,51283.0,NaN,middle_east,2,0.57,0
7,social_media,NaN,5,62975.0,student,europe,4,0.62,1
8,referral,healthcare,4,38648.0,unemployed,south_america,2,0.86,1

In [771]:
df[numerical].corrwith(df.converted)

number_of_courses_viewed    0.435914
interaction_count           0.374573
lead_score                  0.193673
dtype: float64

In [772]:
correlation_matrix = df[numerical].corr()
correlation_matrix

,number_of_courses_viewed,interaction_count,lead_score
number_of_courses_viewed,1.000000,-0.023565,-0.004879
interaction_count,-0.023565,1.000000,0.009888
lead_score,-0.004879,0.009888,1.000000

In [773]:
df_temp, df_train, y_temp, y_train = train_test_split(
    df_filled.drop('converted', axis=1), 
    df_filled['converted'], 
    test_size=0.6,  
    random_state=42, 
    stratify=df_filled['converted']
)

In [774]:
df_val.isnull().sum()

lead_source                  0
industry                     0
number_of_courses_viewed     0
annual_income               37
employment_status            0
location                     0
interaction_count            0
lead_score                   0
dtype: int64

In [775]:
df_val, df_test, y_val, y_test = train_test_split(
    df_temp, y_temp,
    test_size=0.5,  
    random_state=42,
    stratify=y_temp
)
df_test

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,lead_source,industry,number_of_courses_viewed,annual_income,employment_status,location,interaction_count,lead_score
1363,organic_search,retail,2,67187.0,self_employed,middle_east,4,0.37
663,events,manufacturing,4,75559.0,self_employed,south_america,2,0.72
427,referral,healthcare,0,70164.0,employed,asia,4,0.35
1027,events,healthcare,2,48075.0,unemployed,asia,4,0.74
795,social_media,NA,3,49364.0,student,north_america,2,0.58
...,...,...,...,...,...,...,...,...
981,social_media,healthcare,1,64084.0,unemployed,middle_east,0,0.41
696,referral,retail,4,NaN,student,australia,2,0.49
447,events,education,0,49003.0,self_employed,south_america,5,0.32
474,referral,healthcare,0,48902.0,student,south_america,4,0.36
680,paid_ads,retail,3,61585.0,unemployed,south_america,2,0.41

In [776]:
mutual_info_score(df_full_train.converted, df_full_train.interaction_count)

0.0871285827253218

In [777]:
def mutual_info_converted_score(series):
    return mutual_info_score(series, df_full_train.converted)

In [778]:
score = df_full_train[categorical].apply(mutual_info_converted_score)
score.sort_values(ascending=False)
round(score,2)

lead_source          0.02
industry             0.01
employment_status    0.01
location             0.00
dtype: float64

In [779]:
dv = DictVectorizer(sparse=False)

dv = DictVectorizer(sparse=False)
X_train = dv.fit_transform(df_train[features].to_dict(orient='records'))
X_val = dv.transform(df_val[features].to_dict(orient='records'))

In [780]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [781]:
model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
model.fit(X_train,y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [782]:
model.intercept_[0]

-3.641129230502741

In [783]:
model.coef_[0].round(2)

array([-1.  ,  0.21, -0.4 , -0.73, -1.72, -0.68,  0.19, -0.19, -0.93,
       -0.12, -0.57, -0.62, -0.73,  1.02,  2.47, -0.63, -0.41, -0.67,
       -1.74,  0.61, -0.8 , -0.26, -0.97, -0.67, -0.25, -0.09, -0.61,
       -0.62, -0.18,  1.34])

In [784]:
y_pred = model.predict_proba(X_val)[:,1]
y_pred

array([1.69732326e-01, 3.81331915e-01, 8.42720953e-01, 4.86434109e-01,
       8.36838188e-01, 8.64270261e-01, 9.51090757e-01, 9.62513847e-01,
       4.83765660e-01, 1.37271858e-01, 9.25138302e-01, 6.08772997e-01,
       2.52915899e-01, 7.10950180e-01, 9.95528958e-01, 9.96799486e-01,
       8.47033896e-01, 7.88374103e-01, 9.94855587e-01, 6.27697998e-01,
       6.99231718e-01, 2.35670484e-02, 4.97339541e-02, 3.27494331e-01,
       9.64638322e-03, 9.98042764e-01, 3.21783926e-01, 9.99899718e-01,
       9.70305736e-01, 3.60067085e-01, 6.31991893e-01, 8.44175307e-01,
       8.57593900e-01, 4.82868320e-01, 2.09932695e-01, 6.97411932e-01,
       9.99060107e-01, 9.72652869e-01, 7.80623533e-01, 8.69618565e-03,
       7.79447822e-02, 9.60819897e-01, 7.84869625e-01, 6.53396648e-01,
       9.74498292e-01, 9.93647392e-01, 8.72906930e-01, 9.02778633e-01,
       9.65636677e-01, 4.68476308e-01, 3.81422655e-01, 3.79438497e-01,
       9.71238779e-01, 1.19204293e-01, 2.10362008e-01, 9.51172218e-01,
       4.85190310e-02, 3.26225655e-01, 4.29303956e-01, 7.99841164e-01,
       9.70623809e-01, 7.15662527e-01, 4.08327096e-01, 1.06747158e-01,
       8.62656329e-01, 9.91029957e-01, 2.48067523e-01, 9.99318962e-01,
       3.33971387e-01, 5.18279267e-01, 6.03807273e-01, 9.87659318e-01,
       7.30980594e-01, 9.79025986e-01, 5.21797298e-01, 4.05117422e-01,
       9.07309180e-01, 8.07230319e-01, 4.96211193e-02, 9.16985747e-01,
       7.22874151e-01, 9.35836879e-03, 9.25507398e-01, 8.31852492e-01,
       8.50317886e-01, 8.35094023e-01, 8.21938789e-01, 5.74591714e-01,
       7.72543948e-01, 5.01611220e-01, 9.82975089e-01, 9.87411722e-01,
       7.50105891e-01, 1.56330197e-01, 9.75388404e-01, 3.86738203e-01,
       9.52685764e-01, 3.41253642e-01, 9.14678316e-01, 9.99348228e-01,
       9.56905098e-01, 9.66533514e-01, 2.24381092e-01, 7.71123473e-01,
       6.98840653e-01, 9.55909527e-01, 3.92163667e-01, 2.40059905e-01,
       7.07654460e-01, 6.31310445e-01, 4.70364058e-01, 2.58017613e-02,
       9.93482531e-01, 6.97070435e-01, 9.50700358e-01, 4.95515814e-02,
       9.86589729e-01, 9.90822890e-01, 5.43942725e-01, 3.71520160e-01,
       8.71024300e-02, 9.50336381e-01, 1.75563186e-01, 9.41305825e-01,
       8.51471406e-01, 7.66451422e-01, 9.99790995e-01, 9.35288687e-01,
       1.12597099e-01, 6.89257378e-01, 9.57057617e-01, 9.64638761e-01,
       9.63626395e-01, 2.14833978e-01, 9.26131279e-01, 9.52685530e-01,
       4.17307622e-01, 8.55754420e-02, 9.98086358e-01, 1.53244951e-01,
       1.50599776e-01, 9.48154244e-01, 2.84442364e-02, 2.26574392e-01,
       9.90580081e-01, 9.99907257e-01, 5.24850977e-02, 1.79853890e-01,
       6.16418474e-02, 8.63090279e-01, 9.77527578e-01, 9.98605321e-01,
       4.15554676e-01, 4.67666850e-02, 8.40040589e-02, 9.87190666e-01,
       9.98529024e-01, 3.51056862e-01, 2.95387456e-02, 7.26763210e-01,
       7.26802489e-01, 2.73247961e-01, 1.60826861e-02, 3.73903984e-01,
       2.81796691e-01, 3.36037322e-01, 4.32585369e-01, 1.10771649e-01,
       8.88255040e-01, 8.13380753e-01, 9.88089828e-01, 2.91089278e-01,
       9.47433921e-01, 9.99966909e-01, 9.42225869e-04, 2.81022594e-01,
       7.44155275e-01, 2.35808735e-02, 6.95910368e-01, 8.52089352e-01,
       8.43589434e-01, 6.13622479e-02, 8.94830467e-01, 3.14623229e-01,
       9.46360640e-03, 7.89950137e-01, 9.74552736e-01, 9.79525060e-01,
       9.98573321e-01, 9.79418235e-01, 9.69177524e-01, 2.12330454e-02,
       6.90153141e-01, 9.99451483e-01, 3.47634018e-01, 9.42350014e-01,
       8.58160293e-01, 1.56880590e-01, 8.49629978e-01, 9.98142718e-01,
       2.21631168e-01, 8.49777674e-01, 7.09360560e-01, 8.74890584e-01,
       2.98770049e-01, 8.92665088e-01, 2.50125429e-03, 3.92822779e-01,
       2.03289277e-01, 8.96901634e-01, 3.44999449e-02, 8.85332001e-01,
       7.57954260e-01, 9.99626148e-01, 3.41304739e-01, 5.96615143e-01,
       5.26379211e-02, 4.59834209e-01, 6.53865946e-01, 5.41612302e-01,
       9.91530334e-01, 9.72564221e-02, 6.93595605e-01, 4.77675146e-01,
       9.89179976e-01, 9.84208671e-01, 1.16483556e-01, 9.44372414e-01,
       8.32746120e-01, 9.94602049e-01, 9.37731544e-01, 9.28427271e-01,
       5.63643276e-01, 9.99912978e-01, 6.39703018e-01, 9.99458474e-01,
       7.41270223e-01, 2.54261972e-02, 5.41987182e-01, 9.26981690e-01,
       9.22004010e-01, 1.32217902e-01, 9.90076553e-01, 3.52702874e-01,
       6.77586237e-01, 8.59084904e-01, 9.97798651e-01, 2.53117912e-01,
       9.73818292e-01, 7.06281548e-01, 9.66027590e-01, 7.07104661e-01,
       9.34118945e-01, 5.51179920e-01, 3.08358472e-01, 8.55248005e-01,
       3.81989665e-01, 8.66363159e-01, 8.86102396e-02, 9.05210219e-01,
       1.76351537e-01, 5.82697702e-01, 9.85290023e-01, 8.67086220e-01,
       2.37119175e-01, 1.39345381e-01, 3.88511919e-01, 9.48311174e-01,
       7.47157371e-03, 9.68774788e-01, 9.34907691e-01, 9.19653768e-01,
       1.70869581e-01, 9.83237809e-01, 9.72251306e-01, 9.48199945e-01,
       9.36793222e-01, 9.98108438e-01, 3.09103772e-02, 1.01088361e-01,
       9.76863504e-01, 9.99165495e-01, 9.78888888e-01, 7.93517510e-01,
       9.32721546e-01, 9.76350752e-01, 9.93721274e-01, 6.32063362e-01,
       8.63191827e-01, 9.90986765e-01, 1.53279683e-01, 4.33825296e-01])

In [785]:
y_pred_val = model.predict(X_val)

accuracy = (y_pred_val == y_val).mean()
round(accuracy, 2)

0.86

In [786]:
accuracy

0.8561643835616438

In [787]:
baseline_accuracy = accuracy

In [788]:
accuracy

0.8561643835616438

In [789]:
features
feature_importance = {}

In [790]:
features_to_check = ['industry', 'employment_status', 'lead_score']
drops = {f: feature_importance[f] for f in features_to_check}
least_useful = min(drops, key=drops.get)
print("Answer:", least_useful)

KeyError: 'industry'

In [ ]:
dicts_full_train = df_full_train[categorical + numerical].to_dict(orient='records')
dv = DictVectorizer(sparse=False)
X_full_train = dv.fit_transform(dicts_full_train)
y_full_train = df_full_train['converted'].values


dicts_test = df_test[categorical + numerical].to_dict(orient='records')
X_test = dv.transform(dicts_test)


best_acc = 0
best_C = None
for C in [0.01, 0.1, 1, 10, 100]:
    model = LogisticRegression(solver='liblinear', C=C, max_iter=1000, random_state=42)
    model.fit(X_train, y_train)
    acc = (model.predict(X_val) == y_val).mean()
    if acc > best_acc:
        best_acc = acc
        best_C = C
print(f"Best C: {best_C}, Accuracy: {best_acc:.3f}")